// EngineCoordinator.swift
// macMLX
//
// @Observable façade over the active InferenceEngine. SwiftUI views observe
// `status` and `currentModel` for live updates; load/unload/generate go
// through the coordinator so the rest of the app never holds a direct
// reference to a specific engine implementation.

import Foundation
import MacMLXCore

@Observable
@MainActor
public final class EngineCoordinator {

    // MARK: - Public state

    public private(set) var status: EngineStatus = .idle
    public private(set) var currentModel: LocalModel?
    public private(set) var engineID: EngineID = .mlxSwift

    /// Active engine's `version` string (e.g. `"mlx-swift-lm 3.31.3"`),
    /// cached synchronously on the @MainActor so SwiftUI views and the
    /// benchmark feature can read it without awaiting the engine actor.
    /// Refreshed on every `switchTo(_:)`; empty string if no engine is
    /// wired (detection-only engines).
    public private(set) var engineVersion: String = ""

    /// Tokens generated by the current process — used for the menu bar
    /// "Tokens today" counter (resets on app restart, not on midnight).
    public private(set) var tokensGeneratedTotal: Int = 0

    /// Hook invoked after a successful `load(_:)` finishes — used by
    /// `AppState` to re-hydrate per-model state (e.g. the Parameters
    /// Inspector's overrides via `ParametersViewModel.loadForModel`) so
    /// features that don't explicitly open the Inspector still see their
    /// persisted values. Fires on the @MainActor; receivers don't need
    /// to hop.
    var onModelLoaded: (@MainActor (LocalModel) async -> Void)?

    // MARK: - Private state

    private var engine: (any InferenceEngine)?

    /// Current active engine, exposed to lifecycle consumers like the
    /// HummingbirdServer that need an `any InferenceEngine` reference.
    /// Nonisolated-read-only snapshot — callers should not mutate.
    public var activeEngine: (any InferenceEngine)? { engine }

    private let logs: LogManager

    // MARK: - Init

    public init(logs: LogManager) {
        self.logs = logs
        self.engine = MLXSwiftEngine()
        self.engineID = .mlxSwift
        Task { [weak self] in await self?.refreshEngineVersion() }
    }

    // MARK: - Engine selection

    /// Swap to a different engine implementation. v0.1 only supports
    /// `.mlxSwift` (in-process); the other two are detection-only stubs.
    public func switchTo(_ id: EngineID) {
        engineID = id
        switch id {
        case .mlxSwift:
            engine = MLXSwiftEngine()
        case .swiftLM, .pythonMLX:
            // v0.1 detection only — leave engine nil so load() fails fast.
            engine = nil
        }
        Task { [weak self] in await self?.refreshEngineVersion() }
    }

    /// Pull the active engine's `version` string onto the coordinator's
    /// synchronous state. Called on init + after every `switchTo(_:)`.
    private func refreshEngineVersion() async {
        guard let engine else { engineVersion = ""; return }
        engineVersion = await engine.version
    }

    // MARK: - Lifecycle

    /// Load a local model into the active engine.
    @discardableResult
    public func load(_ model: LocalModel) async -> Result<Void, Error> {
        guard let engine else {
            let err = EngineError.unsupportedOperation(
                "Engine \(engineID.rawValue) is detection-only in v0.1"
            )
            status = .error(err.localizedDescription)
            return .failure(err)
        }
        status = .loading(model: model.id)
        await logs.log("Loading model: \(model.id)", level: .info, category: .engine)
        do {
            try await engine.load(model)
            currentModel = model
            status = .ready(model: model.id)
            await logs.log("Model loaded: \(model.id)", level: .info, category: .engine)
            // Fire the post-load hook so AppState can rehydrate per-model
            // state (e.g. Parameters Inspector overrides) even if the
            // user never opens the Inspector view.
            await onModelLoaded?(model)
            return .success(())
        } catch {
            status = .error(error.localizedDescription)
            await logs.log(
                "Model load failed: \(error.localizedDescription)",
                level: .error,
                category: .engine
            )
            return .failure(error)
        }
    }

    /// Blow away the prompt cache — both hot and cold tiers. Exposed
    /// to Settings' "Clear All KV Caches" button.
    ///
    /// Today only the in-process `MLXSwiftEngine` carries a prompt
    /// cache; the SwiftLM / Python-MLX detection-only stubs don't, so
    /// downcasting and no-op-on-mismatch is the right shape. When
    /// another engine grows a cache this will move onto the
    /// `InferenceEngine` protocol.
    public func clearPromptCache() async {
        guard let engine = engine as? MLXSwiftEngine else { return }
        await engine.clearPromptCache()
    }

    /// Release the loaded model.
    public func unload() async {
        guard let engine else { return }
        try? await engine.unload()
        currentModel = nil
        status = .idle
        await logs.log("Engine unloaded", level: .info, category: .engine)
    }

    /// Stream tokens for `request` against the active engine. Returns an
    /// empty stream that finishes immediately if no engine is wired.
    public func generate(_ request: GenerateRequest) -> AsyncThrowingStream<GenerateChunk, Error> {
        guard let engine else {
            return AsyncThrowingStream { continuation in
                continuation.finish(throwing: EngineError.modelNotLoaded)
            }
        }
        let stream = engine.generate(request)
        // Wrap to bump the token counter as chunks arrive.
        return AsyncThrowingStream { continuation in
            Task { @MainActor in
                self.status = .generating
                do {
                    for try await chunk in stream {
                        if let usage = chunk.usage {
                            self.tokensGeneratedTotal += usage.completionTokens
                        }
                        continuation.yield(chunk)
                    }
                    continuation.finish()
                    if let model = self.currentModel {
                        self.status = .ready(model: model.id)
                    } else {
                        self.status = .idle
                    }
                } catch {
                    continuation.finish(throwing: error)
                    self.status = .error(error.localizedDescription)
                }
            }
        }
    }
}
