// EngineCoordinator.swift
// macMLX
//
// @Observable façade over the active InferenceEngine. SwiftUI views observe
// `status` and `currentModel` for live updates; load/unload/generate go
// through the coordinator so the rest of the app never holds a direct
// reference to a specific engine implementation.
//
// v0.4+: the coordinator delegates model lifecycle to a `ModelPool` actor
// so previously-loaded (non-pinned) models stay resident until the pool's
// byte budget forces LRU eviction. Single-active-model UX is preserved —
// `currentModel` / `activeEngine` point at the most-recently-loaded
// entry and drive the toolbar + menu bar.

import Foundation
import MacMLXCore

@Observable
@MainActor
public final class EngineCoordinator {

    // MARK: - Public state

    public private(set) var status: EngineStatus = .idle
    public private(set) var currentModel: LocalModel?
    public private(set) var engineID: EngineID = .mlxSwift

    /// Active engine's `version` string (e.g. `"mlx-swift-lm 3.31.3"`),
    /// cached synchronously on the @MainActor so SwiftUI views and the
    /// benchmark feature can read it without awaiting the engine actor.
    /// Refreshed on every `switchTo(_:)` / `load(_:)`; empty string if
    /// no engine is wired (detection-only engines).
    public private(set) var engineVersion: String = ""

    /// Tokens generated by the current process — used for the menu bar
    /// "Tokens today" counter (resets on app restart, not on midnight).
    public private(set) var tokensGeneratedTotal: Int = 0

    /// Hook invoked after a successful `load(_:)` finishes — used by
    /// `AppState` to re-hydrate per-model state (e.g. the Parameters
    /// Inspector's overrides via `ParametersViewModel.loadForModel`) so
    /// features that don't explicitly open the Inspector still see their
    /// persisted values. Fires on the @MainActor; receivers don't need
    /// to hop.
    var onModelLoaded: (@MainActor (LocalModel) async -> Void)?

    // MARK: - Private state

    /// Pool of resident engines. Single-model-at-a-time UX is preserved
    /// because we only call `pool.load` when `currentModel` changes;
    /// ModelPool lazily keeps previously-loaded ones resident (subject
    /// to its byte budget) so the next switch-back skips disk read.
    private let pool: ModelPool

    /// ID of the model the GUI currently treats as active. `nil` when
    /// no model has been loaded (or when the last load was for a
    /// detection-only engine).
    private var currentModelID: String?

    /// Current active engine, exposed to lifecycle consumers like the
    /// HummingbirdServer that need an `any InferenceEngine` reference.
    /// Async because the pool is an actor — callers must `await`.
    public var activeEngine: (any InferenceEngine)? {
        get async {
            guard let id = currentModelID else { return nil }
            return await pool.engine(for: id)
        }
    }

    private let logs: LogManager

    /// Live prompt-cache budget read by the pool factory each time it mints an
    /// engine. Boxed because the coordinator is built in `AppState.init` before
    /// settings are read from disk, and the factory can't await `SettingsManager`
    /// — the real budget is pushed in once at bootstrap via
    /// ``updatePromptCacheConfig(_:)``.
    private let promptCacheConfigBox: PromptCacheConfigBox

    // MARK: - Init

    /// - Parameters:
    ///   - siliconObserver: optional W3 silicon-metrics seam. When provided,
    ///     every `MLXSwiftEngine` the pool mints reports its prefill → decode →
    ///     complete phase timeline to this observer (the `SiliconMonitor`),
    ///     feeding the observation panel's bottleneck classifier. `nil` (the
    ///     default) keeps the pre-W3 behaviour byte-for-byte: no observer
    ///     attached, generation path unchanged.
    ///   - promptCache: initial prompt-cache budget for engines minted before
    ///     ``updatePromptCacheConfig(_:)`` runs. Defaults to the safe production
    ///     defaults; `AppState.bootstrap` pushes the user's persisted values in
    ///     right after settings load.
    public init(
        logs: LogManager,
        siliconObserver: (any SiliconEngineObserver)? = nil,
        promptCache: PromptCacheConfig = PromptCacheConfig()
    ) {
        self.logs = logs
        self.engineID = .mlxSwift
        let configBox = PromptCacheConfigBox(promptCache)
        self.promptCacheConfigBox = configBox
        // Default budget: 50% of total RAM (10^9 GB — Apple convention).
        // Task 4 will persist this in SettingsManager and push updates
        // through `setPoolBudget(bytes:)`.
        let totalGB = MemoryProbe.totalMemoryGB()
        let budgetGB = max(4.0, totalGB * 0.5)
        let budgetBytes = Int64(budgetGB * 1_000_000_000)
        // Capture the Sendable observer + config box into the @Sendable pool
        // factory so each freshly-minted engine reports its phase timeline and
        // reads the current prompt-cache budget. Passing nil observer resolves
        // to MLXSwiftEngine's own default (observer-free).
        self.pool = ModelPool(maxBytes: budgetBytes) { _ in
            MLXSwiftEngine(siliconObserver: siliconObserver, promptCache: configBox.current)
        }
    }

    // MARK: - Engine selection

    /// Swap to a different engine implementation. v0.1 only supports
    /// `.mlxSwift` (in-process); the other two are detection-only stubs.
    /// Changing engineID alone doesn't affect the pool — the pool's
    /// factory still produces `MLXSwiftEngine` instances because that's
    /// the only real engine in v0.4. Detection-only engines cause
    /// `load(_:)` to fail fast at status check time.
    public func switchTo(_ id: EngineID) {
        engineID = id
        Task { [weak self] in await self?.refreshEngineVersion() }
    }

    /// Pull the active engine's `version` string onto the coordinator's
    /// synchronous state. Called on init + after every `switchTo(_:)`
    /// / successful `load(_:)`.
    private func refreshEngineVersion() async {
        guard let id = currentModelID,
              let engine = await pool.engine(for: id) else {
            engineVersion = ""
            return
        }
        engineVersion = await engine.version
    }

    // MARK: - Lifecycle

    /// Load a local model through the pool. The previously-loaded
    /// model stays resident (subject to LRU + byte budget); only the
    /// newly-loaded model becomes the `currentModel`. Detection-only
    /// engines (`.swiftLM`, `.pythonMLX`) fail fast since the pool's
    /// factory always produces `MLXSwiftEngine`.
    @discardableResult
    public func load(
        _ model: LocalModel,
        adapter: LocalAdapter? = nil
    ) async -> Result<Void, Error> {
        guard engineID == .mlxSwift else {
            let err = EngineError.unsupportedOperation(
                "Engine \(engineID.rawValue) is detection-only in v0.1"
            )
            status = .error(err.localizedDescription)
            return .failure(err)
        }
        // POOL-1: remember who was current before this swap so we can
        // unpin them once the new model is successfully pinned.
        let previousModelID = currentModelID
        status = .loading(model: model.id)
        await logs.log("Loading model: \(model.id)", level: .info, category: .engine)
        do {
            // Feed the model's configured idle TTL (v0.5.1) into the pool so
            // `sweepIdle` can reclaim it once idle past `ttlSeconds`. Fresh
            // store mirrors how HummingbirdServer loads per-model params.
            let params = await ModelParametersStore().load(for: model.id)
            let engine = try await pool.load(model, ttlSeconds: params.ttlSeconds)

            // Layer the LoRA adapter on top of the freshly-loaded
            // base model (v0.5+). Engines that don't support adapters
            // (CPU stubs, future Python engines) get the protocol-
            // extension default no-op; MLXSwiftEngine routes through
            // LoRAContainer.from(directory:) + auto-PEFT-conversion.
            if let adapter {
                try await engine.applyAdapter(adapter)
                await logs.log(
                    "LoRA adapter applied: \(adapter.name) (format=\(adapter.format.rawValue))",
                    level: .info,
                    category: .engine
                )
            }

            currentModel = model
            currentModelID = model.id
            status = .ready(model: model.id)
            await refreshEngineVersion()
            await logs.log("Model loaded: \(model.id)", level: .info, category: .engine)
            // Fire the post-load hook so AppState can rehydrate per-model
            // state (e.g. Parameters Inspector overrides) even if the
            // user never opens the Inspector view.
            await onModelLoaded?(model)

            // POOL-1: pin the newly-active model so the pool's LRU/budget
            // eviction never reclaims the model the GUI currently treats
            // as current, then unpin whichever model was previously
            // current (if different) — only the single active model is
            // GUI-pinned at a time; other resident models stay eligible
            // for eviction under pressure.
            await pool.setPinned(model.id, true)
            if let previousModelID, previousModelID != model.id {
                await pool.setPinned(previousModelID, false)
            }
            return .success(())
        } catch {
            status = .error(error.localizedDescription)
            await logs.log(
                "Model load failed: \(error.localizedDescription)",
                level: .error,
                category: .engine
            )
            // POOL-1: a failed load(B) may have evicted A (the previously
            // current model) to make room before B's own load threw. If A
            // is no longer resident, `currentModel`/`currentModelID` would
            // otherwise keep pointing at a dangling entry — a subsequent
            // `generate()` call would throw `.modelNotLoaded` while other
            // UI surfaces still saw a (stale) non-nil `currentModel`.
            // Reconcile: clear the pointer when residency confirms the
            // old model is actually gone.
            if let id = currentModelID {
                let stillResident = await pool.residentModelIDs().contains(id)
                if !stillResident {
                    currentModel = nil
                    currentModelID = nil
                    engineVersion = ""
                }
            }
            return .failure(error)
        }
    }

    /// Blow away the prompt cache — both hot and cold tiers. Exposed
    /// to Settings' "Clear All KV Caches" button.
    ///
    /// v0.4: iterates every resident engine in the pool, so caches
    /// belonging to non-current models also get flushed. Non-MLX
    /// engines (future/detection-only) are skipped via `as?`.
    public func clearPromptCache() async {
        for id in await pool.residentModelIDs() {
            if let mlx = await pool.engine(for: id) as? MLXSwiftEngine {
                await mlx.clearPromptCache()
            }
        }
    }

    /// Release the currently-active model from the pool.
    ///
    /// v0.4 semantics: this unloads **only** `currentModel`; other
    /// previously-loaded models stay resident in the pool. That's the
    /// main user-visible v0.4 improvement — cold-switching back to a
    /// recent model no longer re-reads weights from disk.
    public func unload() async {
        guard let id = currentModelID else { return }
        await pool.unload(id)
        currentModelID = nil
        currentModel = nil
        status = .idle
        engineVersion = ""
        await logs.log("Engine unloaded", level: .info, category: .engine)
    }

    /// Stream tokens for `request` against the active engine. Returns an
    /// empty stream that finishes immediately if no model is loaded.
    public func generate(_ request: GenerateRequest) -> AsyncThrowingStream<GenerateChunk, Error> {
        let pool = self.pool
        let currentID = self.currentModelID
        return AsyncThrowingStream { continuation in
            let task = Task { @MainActor in
                guard let id = currentID else {
                    // Nothing was ever current — no model to generate against.
                    continuation.finish(throwing: EngineError.modelNotLoaded)
                    return
                }
                guard let engine = await pool.engine(for: id) else {
                    // Residency miss (P3-6): `id` was our current model but the
                    // pool no longer has it resident — evicted under budget
                    // pressure, or unloaded concurrently. Finish the stream as
                    // not-loaded AND reconcile the observable state; otherwise
                    // `status` stays a stale `.ready` and the toolbar / menu bar
                    // keep showing a phantom current model that can't answer.
                    // Mirrors the failed-load reconcile in `load(_:)`.
                    continuation.finish(throwing: EngineError.modelNotLoaded)
                    // Reconcile ONLY when the missing model is still the
                    // current one. In the stale-id race (this generation
                    // captured id A, the user has since loaded healthy B)
                    // touching `status` here would clobber B's `.ready` with
                    // a phantom error.
                    if self.currentModelID == id {
                        self.currentModel = nil
                        self.currentModelID = nil
                        self.engineVersion = ""
                        self.status = .error(EngineError.modelNotLoaded.localizedDescription)
                    }
                    return
                }
                self.status = .generating
                // Register this generation in the pool's in-flight refcount
                // so a concurrent `load(_:)`'s idle sweep / budget evict can't
                // reclaim this model mid-stream (A4/A3). Balance it on EVERY
                // exit path — success, throw, or cancellation — via a defer
                // that spawns the async end (mirrors the release-lock idiom in
                // HummingbirdServer). Refcounted (not a bool) so an overlapping
                // server generation on the same model can't clear it early.
                await pool.beginGenerating(id)
                defer { Task { await pool.endGenerating(id) } }
                do {
                    for try await chunk in engine.generate(request) {
                        if let usage = chunk.usage {
                            self.tokensGeneratedTotal += usage.completionTokens
                        }
                        // POOL-2 (H7): honor the yield result instead of
                        // discarding it. `.terminated` means the consumer
                        // stopped listening (e.g. Stop cancelled its
                        // iteration) — stop pulling from the engine instead
                        // of draining it to completion regardless.
                        if case .terminated = continuation.yield(chunk) {
                            break
                        }
                    }
                    continuation.finish()
                    if let model = self.currentModel {
                        self.status = .ready(model: model.id)
                    } else {
                        self.status = .idle
                    }
                } catch {
                    continuation.finish(throwing: error)
                    self.status = .error(error.localizedDescription)
                }
            }
            // POOL-2 (H7): propagate this stream's termination — including
            // the consumer's task being cancelled (GUI Stop button) — down
            // into the Task driving generation. Without this, cancelling
            // only the CONSUMER left this Task (and the engine's own
            // generation loop) running to maxTokens/EOS, burning GPU and
            // still writing the prompt cache after Stop was pressed.
            continuation.onTermination = { @Sendable _ in
                task.cancel()
            }
        }
    }

    // MARK: - Pool pass-throughs (v0.4)

    /// Pin / unpin a resident model so the LRU sweeper won't evict it
    /// when the pool's byte budget is exceeded. No-op for models that
    /// aren't currently resident.
    public func setPinned(_ modelID: String, _ pinned: Bool) async {
        await pool.setPinned(modelID, pinned)
    }

    /// Mark/unmark `modelID` as actively generating in the pool (POOL-3).
    /// Used as the HTTP server's in-flight hook (`HummingbirdServer.InFlightHook`)
    /// so a concurrent GUI `load(_:)` can't evict a model the server is
    /// mid-stream against — mirrors the guard `generate(_:)` above already
    /// applies for the GUI chat path. Translates the hook's bool `active`
    /// shape onto the pool's refcount (A3): `true` begins a generation,
    /// `false` ends one, so overlapping GUI-chat + server generations on the
    /// same model each keep the entry protected until BOTH have finished.
    public func setGenerating(_ modelID: String, _ active: Bool) async {
        if active {
            await pool.beginGenerating(modelID)
        } else {
            await pool.endGenerating(modelID)
        }
    }

    /// IDs of every currently-resident model in the pool (sorted).
    /// Used by the Models tab to render the "loaded" indicator and
    /// by Settings' pool-stats panel (Task 4).
    public func residentModelIDs() async -> [String] {
        await pool.residentModelIDs()
    }

    /// Update the pool's byte budget. Called by the Settings
    /// "Max resident memory" slider (Task 4). Shrinking the budget
    /// below current usage doesn't synchronously evict — eviction
    /// happens on the next `load(_:)`.
    public func setPoolBudget(bytes: Int64) async {
        await pool.setMaxBytes(bytes)
    }

    /// Push the persisted prompt-cache budget into the pool factory so every
    /// engine minted *after* this call uses it. Called from `AppState.bootstrap`
    /// right after settings load — before any model can be loaded — so the real
    /// budget applies from the first-ever engine. Engines already resident keep
    /// the config they were built with (at bootstrap there are none). Mirrors
    /// the `setPoolBudget` push idiom for the model pool.
    public func updatePromptCacheConfig(_ config: PromptCacheConfig) {
        promptCacheConfigBox.set(config)
    }
}

/// Thread-safe holder for the prompt-cache budget the (synchronous, `@Sendable`)
/// pool factory reads when minting each engine. `@unchecked Sendable` with an
/// `NSLock` mirrors the repo's other tiny cross-isolation boxes (e.g.
/// `HFDownloader.SpeedSampler`): the lock carries the synchronisation, the state
/// is a small value type, so a plain lock is the right primitive. `nonisolated`
/// opts the box out of the app target's default `@MainActor` isolation so the
/// `@Sendable` factory closure can read `current` off the main actor.
private nonisolated final class PromptCacheConfigBox: @unchecked Sendable {
    private let lock = NSLock()
    private var value: PromptCacheConfig

    init(_ value: PromptCacheConfig) {
        self.value = value
    }

    var current: PromptCacheConfig {
        lock.lock()
        defer { lock.unlock() }
        return value
    }

    func set(_ new: PromptCacheConfig) {
        lock.lock()
        defer { lock.unlock() }
        value = new
    }
}
