// EngineCoordinator.swift
// macMLX
//
// @Observable façade over the active InferenceEngine. SwiftUI views observe
// `status` and `currentModel` for live updates; load/unload/generate go
// through the coordinator so the rest of the app never holds a direct
// reference to a specific engine implementation.
//
// v0.4+: the coordinator delegates model lifecycle to a `ModelPool` actor
// so previously-loaded (non-pinned) models stay resident until the pool's
// byte budget forces LRU eviction. Single-active-model UX is preserved —
// `currentModel` / `activeEngine` point at the most-recently-loaded
// entry and drive the toolbar + menu bar.

import Foundation
import MacMLXCore

@Observable
@MainActor
public final class EngineCoordinator {

    // MARK: - Public state

    public private(set) var status: EngineStatus = .idle
    public private(set) var currentModel: LocalModel?
    public private(set) var engineID: EngineID = .mlxSwift

    /// Active engine's `version` string (e.g. `"mlx-swift-lm 3.31.3"`),
    /// cached synchronously on the @MainActor so SwiftUI views and the
    /// benchmark feature can read it without awaiting the engine actor.
    /// Refreshed on every `switchTo(_:)` / `load(_:)`; empty string if
    /// no engine is wired (detection-only engines).
    public private(set) var engineVersion: String = ""

    /// Tokens generated by the current process — used for the menu bar
    /// "Tokens today" counter (resets on app restart, not on midnight).
    public private(set) var tokensGeneratedTotal: Int = 0

    /// Hook invoked after a successful `load(_:)` finishes — used by
    /// `AppState` to re-hydrate per-model state (e.g. the Parameters
    /// Inspector's overrides via `ParametersViewModel.loadForModel`) so
    /// features that don't explicitly open the Inspector still see their
    /// persisted values. Fires on the @MainActor; receivers don't need
    /// to hop.
    var onModelLoaded: (@MainActor (LocalModel) async -> Void)?

    // MARK: - Private state

    /// Pool of resident engines. Single-model-at-a-time UX is preserved
    /// because we only call `pool.load` when `currentModel` changes;
    /// ModelPool lazily keeps previously-loaded ones resident (subject
    /// to its byte budget) so the next switch-back skips disk read.
    private let pool: ModelPool

    /// ID of the model the GUI currently treats as active. `nil` when
    /// no model has been loaded (or when the last load was for a
    /// detection-only engine).
    private var currentModelID: String?

    /// Current active engine, exposed to lifecycle consumers like the
    /// HummingbirdServer that need an `any InferenceEngine` reference.
    /// Async because the pool is an actor — callers must `await`.
    public var activeEngine: (any InferenceEngine)? {
        get async {
            guard let id = currentModelID else { return nil }
            return await pool.engine(for: id)
        }
    }

    private let logs: LogManager

    // MARK: - Init

    public init(logs: LogManager) {
        self.logs = logs
        self.engineID = .mlxSwift
        // Default budget: 50% of total RAM (10^9 GB — Apple convention).
        // Task 4 will persist this in SettingsManager and push updates
        // through `setPoolBudget(bytes:)`.
        let totalGB = MemoryProbe.totalMemoryGB()
        let budgetGB = max(4.0, totalGB * 0.5)
        let budgetBytes = Int64(budgetGB * 1_000_000_000)
        self.pool = ModelPool(maxBytes: budgetBytes) { _ in
            MLXSwiftEngine()
        }
    }

    // MARK: - Engine selection

    /// Swap to a different engine implementation. v0.1 only supports
    /// `.mlxSwift` (in-process); the other two are detection-only stubs.
    /// Changing engineID alone doesn't affect the pool — the pool's
    /// factory still produces `MLXSwiftEngine` instances because that's
    /// the only real engine in v0.4. Detection-only engines cause
    /// `load(_:)` to fail fast at status check time.
    public func switchTo(_ id: EngineID) {
        engineID = id
        Task { [weak self] in await self?.refreshEngineVersion() }
    }

    /// Pull the active engine's `version` string onto the coordinator's
    /// synchronous state. Called on init + after every `switchTo(_:)`
    /// / successful `load(_:)`.
    private func refreshEngineVersion() async {
        guard let id = currentModelID,
              let engine = await pool.engine(for: id) else {
            engineVersion = ""
            return
        }
        engineVersion = await engine.version
    }

    // MARK: - Lifecycle

    /// Load a local model through the pool. The previously-loaded
    /// model stays resident (subject to LRU + byte budget); only the
    /// newly-loaded model becomes the `currentModel`. Detection-only
    /// engines (`.swiftLM`, `.pythonMLX`) fail fast since the pool's
    /// factory always produces `MLXSwiftEngine`.
    @discardableResult
    public func load(_ model: LocalModel) async -> Result<Void, Error> {
        guard engineID == .mlxSwift else {
            let err = EngineError.unsupportedOperation(
                "Engine \(engineID.rawValue) is detection-only in v0.1"
            )
            status = .error(err.localizedDescription)
            return .failure(err)
        }
        status = .loading(model: model.id)
        await logs.log("Loading model: \(model.id)", level: .info, category: .engine)
        do {
            _ = try await pool.load(model)
            currentModel = model
            currentModelID = model.id
            status = .ready(model: model.id)
            await refreshEngineVersion()
            await logs.log("Model loaded: \(model.id)", level: .info, category: .engine)
            // Fire the post-load hook so AppState can rehydrate per-model
            // state (e.g. Parameters Inspector overrides) even if the
            // user never opens the Inspector view.
            await onModelLoaded?(model)
            return .success(())
        } catch {
            status = .error(error.localizedDescription)
            await logs.log(
                "Model load failed: \(error.localizedDescription)",
                level: .error,
                category: .engine
            )
            return .failure(error)
        }
    }

    /// Blow away the prompt cache — both hot and cold tiers. Exposed
    /// to Settings' "Clear All KV Caches" button.
    ///
    /// v0.4: iterates every resident engine in the pool, so caches
    /// belonging to non-current models also get flushed. Non-MLX
    /// engines (future/detection-only) are skipped via `as?`.
    public func clearPromptCache() async {
        for id in await pool.residentModelIDs() {
            if let mlx = await pool.engine(for: id) as? MLXSwiftEngine {
                await mlx.clearPromptCache()
            }
        }
    }

    /// Release the currently-active model from the pool.
    ///
    /// v0.4 semantics: this unloads **only** `currentModel`; other
    /// previously-loaded models stay resident in the pool. That's the
    /// main user-visible v0.4 improvement — cold-switching back to a
    /// recent model no longer re-reads weights from disk.
    public func unload() async {
        guard let id = currentModelID else { return }
        await pool.unload(id)
        currentModelID = nil
        currentModel = nil
        status = .idle
        engineVersion = ""
        await logs.log("Engine unloaded", level: .info, category: .engine)
    }

    /// Stream tokens for `request` against the active engine. Returns an
    /// empty stream that finishes immediately if no model is loaded.
    public func generate(_ request: GenerateRequest) -> AsyncThrowingStream<GenerateChunk, Error> {
        let pool = self.pool
        let currentID = self.currentModelID
        return AsyncThrowingStream { continuation in
            Task { @MainActor in
                guard let id = currentID,
                      let engine = await pool.engine(for: id) else {
                    continuation.finish(throwing: EngineError.modelNotLoaded)
                    return
                }
                self.status = .generating
                do {
                    for try await chunk in engine.generate(request) {
                        if let usage = chunk.usage {
                            self.tokensGeneratedTotal += usage.completionTokens
                        }
                        continuation.yield(chunk)
                    }
                    continuation.finish()
                    if let model = self.currentModel {
                        self.status = .ready(model: model.id)
                    } else {
                        self.status = .idle
                    }
                } catch {
                    continuation.finish(throwing: error)
                    self.status = .error(error.localizedDescription)
                }
            }
        }
    }

    // MARK: - Pool pass-throughs (v0.4)

    /// Pin / unpin a resident model so the LRU sweeper won't evict it
    /// when the pool's byte budget is exceeded. No-op for models that
    /// aren't currently resident.
    public func setPinned(_ modelID: String, _ pinned: Bool) async {
        await pool.setPinned(modelID, pinned)
    }

    /// IDs of every currently-resident model in the pool (sorted).
    /// Used by the Models tab to render the "loaded" indicator and
    /// by Settings' pool-stats panel (Task 4).
    public func residentModelIDs() async -> [String] {
        await pool.residentModelIDs()
    }

    /// Update the pool's byte budget. Called by the Settings
    /// "Max resident memory" slider (Task 4). Shrinking the budget
    /// below current usage doesn't synchronously evict — eviction
    /// happens on the next `load(_:)`.
    public func setPoolBudget(bytes: Int64) async {
        await pool.setMaxBytes(bytes)
    }
}
